AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy EC2 Instance without SSH Key"

Parameters:
  Environment:
    Type: String
    Default: "test"
    Description: "Deployment environment (e.g., dev, prod)"

  InstanceType:
    Type: String
    Default: "t2.micro"
    Description: "EC2 instance type"
  SSHDefaultKey:
    Type: String
    Description: "SSH Key"

Resources:
  SSHKey:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: "root_key"
      PublicKeyMaterial: !Ref SSHDefaultKey
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH access from the internet"
      VpcId: !ImportValue
        Fn::Sub: "${Environment}-VPC-ID"  # Ensure you have exported VPC-ID in another stack
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Allow SSH from any IP (Modify this for better security)
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-SSH-SG"

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00354acb6e3508fd0
      InstanceType: !Ref InstanceType
      KeyName: !Ref SSHKey
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId: !ImportValue
            Fn::Sub: "${Environment}-Subnet-ID"
          GroupSet:
            - !Ref SSHSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-EC2"

Outputs:
  EC2InstanceId:
    Description: "Instance ID of EC2"
    Value: !Ref MyEC2Instance

  PublicIP:
    Description: "Public IP of EC2"
    Value: !GetAtt MyEC2Instance.PublicIp
