name: CloudFormation Multi-Stack Deployment

on:
  push:
    branches:
      - main
    paths:
      - "cloudformation/**"
  pull_request:
    branches:
      - main
    paths:
      - "cloudformation/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment (test, dev, prod, etc.)"
        required: true
        default: "test"

permissions:
  id-token: write
  contents: read

jobs:
  deploy_vpc:
    name: Deploy VPC Stack
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/GitHubOIDCRole

      - name: Deploy CloudFormation
        uses: ./.github/actions/deploy-cloudformation
        with:
          STACK_NAME: my-vpc-stack
          TEMPLATE_FILE: cloudformation/templates/vpc.yaml
          PARAMS_FILE: cloudformation/parameters/vpc-params.json

  deploy_rds:
    name: Deploy RDS Stack
    runs-on: ubuntu-latest
    needs: deploy_vpc
    environment: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/GitHubOIDCRole

      - name: Deploy CloudFormation
        uses: ./.github/actions/deploy-cloudformation
        with:
          STACK_NAME: my-rds-stack
          TEMPLATE_FILE: cloudformation/templates/rds.yaml
          PARAMS_FILE: cloudformation/parameters/rds-params.json

      - name: Set RDSSecretARN Output
        id: set_rds_secret
        run: |
          RDS_SECRET_ARN=$(aws cloudformation describe-stacks --stack-name my-rds-stack --query "Stacks[0].Outputs[?OutputKey=='RDSSecretARN'].OutputValue" --output text)
          echo "RDS_SECRET_ARN=$RDS_SECRET_ARN" >> $GITHUB_ENV
          echo "::set-output name=RDSSecretARN::$RDS_SECRET_ARN"

  deploy_ec2:
    name: Deploy EC2 Stack
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/GitHubOIDCRole

      - name: Deploy CloudFormation
        uses: ./.github/actions/deploy-cloudformation
        with:
          STACK_NAME: my-ec2-stack
          TEMPLATE_FILE: cloudformation/templates/ec2.yaml
          PARAMS_FILE: cloudformation/parameters/ec2-params.json
